name: SWEN 755 Backend Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    env:
      PYTHON_RUN: python

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r server/requirements.txt

      - name: Copy config files
        run: |
          cp server/config/github-credentials.yml server/config/db.yml

      - name: Check Python version
        run: ${{ env.PYTHON_RUN }} --version

      # - name: Start server
      #   run: ${{ env.PYTHON_RUN }} server/src/server.py &

      # - name: Wait for server to start
      #   run: sleep 3

      - name: Run unit tests (if any)
        run: ${{ env.PYTHON_RUN }} -m unittest
        working-directory: server

      # - name: Run coverage
      #   run: |
      #     coverage run -m unittest discover tests
      #     coverage report -m
      #   working-directory: server
      
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4.0.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: SWEN-732-G3/TigerBets

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env: 
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}