name: SWEN 755 Backend Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    env:
      PYTHON_RUN: python

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r server\requirements.txt

      # - name: Copy config files
      #   run: |
      #     cp server/config/github-credentials.yml server/config/db.yml

      - name: Check Python version
        run: ${{ env.PYTHON_RUN }} --version

      # - name: Start server
      #   run: ${{ env.PYTHON_RUN }} server/src/server.py &


      - name: launch server
        run: |
          ${{ env.PYTHON_RUN }} server/src/server.py &
          
      - name: Wait for server to start
        run: sleep 3
